<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        <?php echo $pagename; ?>
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-home"></i> RGA</li>
        <li class="active"><i class="<?php echo $pageicon;?>"></i></i> <?php echo $pagename;?></li>
        <li class="active"><i class="<?php echo $subpageicon;?>"></i> <?php echo $subpagename;?></li>
      </ol>
    </section>